.SUFFIXES:

SRC_DIR := ./Examples/Clustered
LDFLAGS := -lm -lpthread
CPPFLAGS := -fopenmp -fgnu-tm -fpermissive -O4 -std=c++11

SRCS=$(wildcard $(SRC_DIR)/*.cpp)

CCS=$(SRCS:.cpp=.cc)

EXES=$(SRCS:.cpp=)

all: $(EXES)

%: %.cc
	mpic++ $(CPPFLAGS) -o $@ -I../../ $< $(LDFLAGS)

%.cc: %.cpp
	./Reenterable -force-use-mem -strict-pre-checks -strict-plc-checks $< $@

clean:
	rm -rf $(CCS)
	rm -rf $(EXES)
